### ISSUE TITLE
Step fails with error "bundler: command not found: test-cloud"

### ISSUE THREAD

**Issue by snydersaurus** [bitrise-steplib/steps-xamarin-test-cloud-for-calabash-ios#8] opened 2016-08-11 19:43 UTC
Have this step running last, after building, archiving -- getting the following failure on Bitrise.io

bundle exec test-cloud submit "/Users/vagrant/deploy/MyApp.ipa" **\* --user=bill.snyder@somewhere.com --devices=8b6a6099 --async --series=master --dsym-file /Users/vagrant/deploy/MyApp.dSYM.zip
bundler: command not found: test-cloud
Install missing gem executables with `bundle install`
test-cloud -- failed

**Comment by viktorbenei** [comment] 2016-08-11 19:45
I believe a `Gemfile` is missing here, or a `gem install`.. 

Anyway, thanks for reporting @snydersaurus !

**Comment by viktorbenei** [comment] 2016-08-11 20:33
Note: there was a `Gemfile` in the repo - can that cause the issue @godrei ? I don't think so, as I don't see any gemfile or gem install in the step, so that's more likely the cause.

**Comment by godrei** [comment] 2016-08-12 08:41
Hi @snydersaurus 
step searches for Gemfile in the repo root, if it finds calls `bundle install` (and expects that gemfile contains `calabash-cucumber` and `xamarin-test-cloud`), if there is no gemfile, the step installs the gems.

@snydersaurus can you confirm that there is a Gemfile in your project's repo root?

@viktorbenei i think step should also check if Gemfile exist and if Gemfile contains the required gems, what do you think?

**Comment by viktorbenei** [comment] 2016-08-12 08:43
Ohh, I see - and yes, I agree, we should check the `Gemfile` and at least print an error if it's not there and what to do, or install the required gem automatically.

**Comment by godrei** [comment] 2016-08-12 15:31
Hi @snydersaurus new version ([0.9.4](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-calabash-ios/releases/tag/0.9.4)) ensures required gems (`calabash-cucumber`, `xamarin-test-cloud`) and will be available in the steplib soon.

**Comment by snydersaurus** [comment] 2016-08-12 16:18
Thanks @godrei!

**Comment by godrei** [comment] 2016-11-09 10:05
Hi @snydersaurus,
i will close this issue, since the 0.9.4 version is available in the steplib. Feel free to reopen it, if this issue still exists in the new version.

**Closed as completed by godrei** 2016-11-09 10:05 UTC
Labels: bug
