### ISSUE TITLE
Cannot add step to native iOS build

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-steplib/steps-xamarin-test-cloud-for-calabash-ios#5] opened 2016-06-22 19:55 UTC
Hi,
I have some Xamarin tests in the Xamarin Test cloud, i want to be able to add this step to my workflow so that I can upload the ipa. 
I can locally do:
`test-cloud submit  ipaFile cloudToken --devices deviceToken --series "master" --locale "en_GB" --user userEmail`
And this works so i would like to do the same for a normal built ipa file. Is there some check to make sure the project is a Xamarin project? if so, i don't think its necessary.

**Comment by Reedyuk** [comment] 2016-06-22 21:06
actually i might just fork and make a pull request for this

**Comment by viktorbenei** [comment] 2016-06-25 06:53
So, the problem is that this step is only available for Xamarin projects right now and you want to use it for non Xamarin apps too? Or is there something else preventing you from using this step for non Xamarin apps?

**Comment by Reedyuk** [comment] 2016-06-25 06:55
Yes that's it. I'm using it for a native ios project not a Xamarin project. I have the command working, but in bitrise its a non supported step for my workflow.

**Comment by viktorbenei** [comment] 2016-06-25 06:57
So the step works as-it-is for non Xamarin apps, right? In that case we'll only have to remove the related project type tag (actually add the ios one too).

In the meantime you can turn off the "Filter by platform" option on bitrise.io when you search for a step. If the toggle is turned off you'll see every step available in the StepLib.

**Comment by Reedyuk** [comment] 2016-06-25 07:21
Yes that's how I am doing it at the moment

**Comment by viktorbenei** [comment] 2016-06-25 08:43
Awesome, we'll release a new version then with the added ios project type tag!

Thanks again for reporting!

**Comment by viktorbenei** [comment] 2016-07-11 14:02
Fixed in v0.9.3, available in the steplib now. Thanks for reporting @Reedyuk !

**Closed as completed by viktorbenei** 2016-07-11 14:02 UTC
Labels: question
